export const PolySafeFactoryAbi = [
  {
    type: 'function',
    name: 'createProxy',
    inputs: [
      { name: 'paymentToken', type: 'address', internalType: 'address' },
      { name: 'payment', type: 'uint256', internalType: 'uint256' },
      { name: 'paymentReceiver', type: 'address', internalType: 'address payable' },
      {
        name: 'createSig',
        type: 'tuple',
        internalType: 'struct SafeProxyFactory.Sig',
        components: [
          { name: 'v', type: 'uint8', internalType: 'uint8' },
          { name: 'r', type: 'bytes32', internalType: 'bytes32' },
          { name: 's', type: 'bytes32', internalType: 'bytes32' },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
] as const;

export const GnosisSafeAbi = [
  {
    type: 'function',
    name: 'execTransaction',
    inputs: [
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'value', type: 'uint256', internalType: 'uint256' },
      { name: 'data', type: 'bytes', internalType: 'bytes' },
      { name: 'operation', type: 'uint8', internalType: 'uint8' },
      { name: 'safeTxGas', type: 'uint256', internalType: 'uint256' },
      { name: 'baseGas', type: 'uint256', internalType: 'uint256' },
      { name: 'gasPrice', type: 'uint256', internalType: 'uint256' },
      { name: 'gasToken', type: 'address', internalType: 'address' },
      { name: 'refundReceiver', type: 'address', internalType: 'address payable' },
      { name: 'signatures', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [{ name: 'success', type: 'bool', internalType: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getTransactionHash',
    inputs: [
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'value', type: 'uint256', internalType: 'uint256' },
      { name: 'data', type: 'bytes', internalType: 'bytes' },
      { name: 'operation', type: 'uint8', internalType: 'uint8' },
      { name: 'safeTxGas', type: 'uint256', internalType: 'uint256' },
      { name: 'baseGas', type: 'uint256', internalType: 'uint256' },
      { name: 'gasPrice', type: 'uint256', internalType: 'uint256' },
      { name: 'gasToken', type: 'address', internalType: 'address' },
      { name: 'refundReceiver', type: 'address', internalType: 'address payable' },
      { name: 'nonce', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'nonce',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'setGuard',
    inputs: [{ name: 'guard', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getOwners',
    inputs: [],
    outputs: [{ name: '', type: 'address[]', internalType: 'address[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isOwner',
    inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getThreshold',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'enableModule',
    inputs: [{ name: 'module', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'isModuleEnabled',
    inputs: [{ name: 'module', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getStorageAt',
    inputs: [
      { name: 'offset', type: 'uint256', internalType: 'uint256' },
      { name: 'length', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bytes', internalType: 'bytes' }],
    stateMutability: 'view',
  },
] as const;

export const BounceAbi = [
  {
    type: 'function',
    name: 'proposeBet',
    inputs: [
      { name: 'safe', type: 'address', internalType: 'address' },
      { name: 'funder', type: 'address', internalType: 'address' },
      { name: 'exchange', type: 'address', internalType: 'address' },
      { name: 'conditionId', type: 'bytes32', internalType: 'bytes32' },
      { name: 'outcomeIndex', type: 'uint8', internalType: 'uint8' },
      { name: 'positionId', type: 'uint256', internalType: 'uint256' },
      { name: 'totalCapital', type: 'uint256', internalType: 'uint256' },
      { name: 'proposerCapitalBps', type: 'uint16', internalType: 'uint16' },
      { name: 'proposerProfitShareBps', type: 'uint16', internalType: 'uint16' },
      { name: 'expiresAt', type: 'uint40', internalType: 'uint40' },
      { name: 'slug', type: 'string', internalType: 'string' },
    ],
    outputs: [{ name: 'betId', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'fundBet',
    inputs: [{ name: 'betId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'cancelBet',
    inputs: [{ name: 'betId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'executeTrade',
    inputs: [
      { name: 'betId', type: 'uint256', internalType: 'uint256' },
      { name: 'maxSpend', type: 'uint256', internalType: 'uint256' },
      { name: 'tradeData', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'sellPosition',
    inputs: [
      { name: 'betId', type: 'uint256', internalType: 'uint256' },
      { name: 'minUsdcOut', type: 'uint256', internalType: 'uint256' },
      { name: 'sellData', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'redeemPosition',
    inputs: [{ name: 'betId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'withdraw',
    inputs: [{ name: 'betId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'sweepSafeToken',
    inputs: [
      { name: 'safe', type: 'address', internalType: 'address' },
      { name: 'token', type: 'address', internalType: 'address' },
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'prepareTrade',
    inputs: [{ name: 'betId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'finalizeTrade',
    inputs: [{ name: 'betId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'unprepareTrade',
    inputs: [{ name: 'betId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getPreparedBetBySafe',
    inputs: [{ name: 'safe', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getBet',
    inputs: [{ name: 'betId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct Bounce.Bet',
        components: [
          { name: 'safe', type: 'address', internalType: 'address' },
          { name: 'proposer', type: 'address', internalType: 'address' },
          { name: 'funder', type: 'address', internalType: 'address' },
          { name: 'exchange', type: 'address', internalType: 'address' },
          { name: 'conditionId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'outcomeIndex', type: 'uint8', internalType: 'uint8' },
          { name: 'indexSet', type: 'uint256', internalType: 'uint256' },
          { name: 'positionId', type: 'uint256', internalType: 'uint256' },
          { name: 'slugHash', type: 'bytes32', internalType: 'bytes32' },
          { name: 'totalCapital', type: 'uint256', internalType: 'uint256' },
          { name: 'proposerCapitalBps', type: 'uint16', internalType: 'uint16' },
          { name: 'proposerProfitShareBps', type: 'uint16', internalType: 'uint16' },
          { name: 'escrowUSDC', type: 'uint256', internalType: 'uint256' },
          { name: 'usdcSpent', type: 'uint256', internalType: 'uint256' },
          { name: 'usdcReceived', type: 'uint256', internalType: 'uint256' },
          { name: 'positionShares', type: 'uint256', internalType: 'uint256' },
          { name: 'proposedAt', type: 'uint40', internalType: 'uint40' },
          { name: 'fundedAt', type: 'uint40', internalType: 'uint40' },
          { name: 'tradedAt', type: 'uint40', internalType: 'uint40' },
          { name: 'closedAt', type: 'uint40', internalType: 'uint40' },
          { name: 'withdrawnAt', type: 'uint40', internalType: 'uint40' },
          { name: 'expiresAt', type: 'uint40', internalType: 'uint40' },
          { name: 'status', type: 'uint8', internalType: 'enum Bounce.BetStatus' },
          { name: 'inFlightUSDC', type: 'uint256', internalType: 'uint256' },
          { name: 'preparedAt', type: 'uint40', internalType: 'uint40' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getActiveBetCount',
    inputs: [{ name: 'safe', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'nextBetId',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'USDC',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'CTF',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'CTF_EXCHANGE',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'NEG_RISK_CTF_EXCHANGE',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'BPS_DENOMINATOR',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'BetProposed',
    inputs: [
      { name: 'betId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'safe', type: 'address', indexed: true, internalType: 'address' },
      { name: 'proposer', type: 'address', indexed: true, internalType: 'address' },
      { name: 'funder', type: 'address', indexed: false, internalType: 'address' },
      { name: 'exchange', type: 'address', indexed: false, internalType: 'address' },
      { name: 'conditionId', type: 'bytes32', indexed: false, internalType: 'bytes32' },
      { name: 'outcomeIndex', type: 'uint8', indexed: false, internalType: 'uint8' },
      { name: 'positionId', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'totalCapital', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'proposerDeposit', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'expiresAt', type: 'uint40', indexed: false, internalType: 'uint40' },
      { name: 'slug', type: 'string', indexed: false, internalType: 'string' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'BetFunded',
    inputs: [
      { name: 'betId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'funder', type: 'address', indexed: true, internalType: 'address' },
      { name: 'funderDeposit', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'BetCancelled',
    inputs: [
      { name: 'betId', type: 'uint256', indexed: true, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TradeExecuted',
    inputs: [
      { name: 'betId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'maxSpend', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'usdcSpentDelta', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'sharesDelta', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PositionSold',
    inputs: [
      { name: 'betId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'sharesSold', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'usdcReceived', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PositionRedeemed',
    inputs: [
      { name: 'betId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'usdcReceived', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'BetClosed',
    inputs: [
      { name: 'betId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'escrowUSDC', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'BetWithdrawn',
    inputs: [
      { name: 'betId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'totalReturned', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'proposerAmount', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'funderAmount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TradePrepared',
    inputs: [
      { name: 'betId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'safe', type: 'address', indexed: true, internalType: 'address' },
      { name: 'amountMoved', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TradeFinalized',
    inputs: [
      { name: 'betId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'usdcSpentDelta', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'sharesDelta', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'usdcLeftoverReturned', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TradeUnprepared',
    inputs: [
      { name: 'betId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'amountReturned', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
] as const;

export const BouncePeripheryAbi = [
  {
    type: 'function',
    name: 'getBetsByProposerCount',
    inputs: [{ name: 'proposer', type: 'address', internalType: 'address' }],
    outputs: [{ name: 'count', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getBetsByProposer',
    inputs: [
      { name: 'proposer', type: 'address', internalType: 'address' },
      { name: 'start', type: 'uint256', internalType: 'uint256' },
      { name: 'end', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256[]', internalType: 'uint256[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getBetsByFunderCount',
    inputs: [{ name: 'funder', type: 'address', internalType: 'address' }],
    outputs: [{ name: 'count', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getBetsByFunder',
    inputs: [
      { name: 'funder', type: 'address', internalType: 'address' },
      { name: 'start', type: 'uint256', internalType: 'uint256' },
      { name: 'end', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256[]', internalType: 'uint256[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getBetsBySafeCount',
    inputs: [{ name: 'safe', type: 'address', internalType: 'address' }],
    outputs: [{ name: 'count', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getBetsBySafe',
    inputs: [
      { name: 'safe', type: 'address', internalType: 'address' },
      { name: 'start', type: 'uint256', internalType: 'uint256' },
      { name: 'end', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256[]', internalType: 'uint256[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getBetsByConditionIdCount',
    inputs: [{ name: 'conditionId', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: 'count', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getBetsByConditionId',
    inputs: [
      { name: 'conditionId', type: 'bytes32', internalType: 'bytes32' },
      { name: 'start', type: 'uint256', internalType: 'uint256' },
      { name: 'end', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256[]', internalType: 'uint256[]' }],
    stateMutability: 'view',
  },
] as const;

export const CTFExchangeAbi = [
  {
    type: 'function',
    name: 'nonces',
    inputs: [{ name: 'usr', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
] as const;
