export const ThesisFactoryV2Abi = [
  {
    type: 'function',
    name: 'createThesis',
    inputs: [
      { name: 'safe', type: 'address', internalType: 'address' },
      { name: 'funder', type: 'address', internalType: 'address' },
      { name: 'proposer', type: 'address', internalType: 'address' },
      { name: 'totalCapital', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: 'settlement', type: 'address', internalType: 'contract ThesisSettlementV2' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'createThesisWithParams',
    inputs: [
      { name: 'safe', type: 'address', internalType: 'address' },
      { name: 'funder', type: 'address', internalType: 'address' },
      { name: 'proposer', type: 'address', internalType: 'address' },
      { name: 'totalCapital', type: 'uint256', internalType: 'uint256' },
      { name: 'proposerCapitalBps', type: 'uint256', internalType: 'uint256' },
      { name: 'proposerProfitShareBps', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: 'settlement', type: 'address', internalType: 'contract ThesisSettlementV2' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'deployGuard',
    inputs: [{ name: 'safe', type: 'address', internalType: 'address' }],
    outputs: [{ name: 'guard', type: 'address', internalType: 'contract ThesisGuardV2' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'manager',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract ThesisManager' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'USDC',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'DEFAULT_PROPOSER_CAPITAL_BPS',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'DEFAULT_PROPOSER_PROFIT_SHARE_BPS',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'ThesisCreated',
    inputs: [
      { name: 'safe', type: 'address', indexed: true, internalType: 'address' },
      { name: 'settlement', type: 'address', indexed: true, internalType: 'address' },
      { name: 'funder', type: 'address', indexed: false, internalType: 'address' },
      { name: 'proposer', type: 'address', indexed: false, internalType: 'address' },
      { name: 'totalCapital', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
  },
  {
    type: 'event',
    name: 'GuardDeployed',
    inputs: [
      { name: 'safe', type: 'address', indexed: true, internalType: 'address' },
      { name: 'guard', type: 'address', indexed: true, internalType: 'address' },
    ],
  },
] as const;

export const ThesisManagerV2Abi = [
  {
    type: 'function',
    name: 'exchangeApprovalCap',
    inputs: [{ name: 'safe', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isActiveSettlement',
    inputs: [
      { name: 'safe', type: 'address', internalType: 'address' },
      { name: 'settlement', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'settlementApprovalCap',
    inputs: [
      { name: 'safe', type: 'address', internalType: 'address' },
      { name: 'settlement', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isApprovedGuard',
    inputs: [
      { name: 'safe', type: 'address', internalType: 'address' },
      { name: 'guard', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'safeGuard',
    inputs: [{ name: 'safe', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalActiveCap',
    inputs: [{ name: 'safe', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'factory',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
] as const;

export const ThesisSettlementV2Abi = [
  {
    type: 'function',
    name: 'proposer',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'funder',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'safe',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'manager',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'usdc',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IERC20' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalCapital',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'proposerCapitalBps',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'proposerProfitShareBps',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'distributed',
    inputs: [],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'distribute',
    inputs: [{ name: '_safe', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'BPS_DENOMINATOR',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
] as const;

export const ThesisGuardV2Abi = [
  {
    type: 'function',
    name: 'manager',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IThesisManager' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'safe',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'USDC',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'CTF',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'CTF_EXCHANGE',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
] as const;

export const PolySafeFactoryAbi = [
  {
    type: 'function',
    name: 'createProxy',
    inputs: [
      { name: 'owner', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: 'proxy', type: 'address', internalType: 'address' }],
    stateMutability: 'nonpayable',
  },
] as const;

export const GnosisSafeAbi = [
  {
    type: 'function',
    name: 'execTransaction',
    inputs: [
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'value', type: 'uint256', internalType: 'uint256' },
      { name: 'data', type: 'bytes', internalType: 'bytes' },
      { name: 'operation', type: 'uint8', internalType: 'uint8' },
      { name: 'safeTxGas', type: 'uint256', internalType: 'uint256' },
      { name: 'baseGas', type: 'uint256', internalType: 'uint256' },
      { name: 'gasPrice', type: 'uint256', internalType: 'uint256' },
      { name: 'gasToken', type: 'address', internalType: 'address' },
      { name: 'refundReceiver', type: 'address', internalType: 'address payable' },
      { name: 'signatures', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [{ name: 'success', type: 'bool', internalType: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getTransactionHash',
    inputs: [
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'value', type: 'uint256', internalType: 'uint256' },
      { name: 'data', type: 'bytes', internalType: 'bytes' },
      { name: 'operation', type: 'uint8', internalType: 'uint8' },
      { name: 'safeTxGas', type: 'uint256', internalType: 'uint256' },
      { name: 'baseGas', type: 'uint256', internalType: 'uint256' },
      { name: 'gasPrice', type: 'uint256', internalType: 'uint256' },
      { name: 'gasToken', type: 'address', internalType: 'address' },
      { name: 'refundReceiver', type: 'address', internalType: 'address payable' },
      { name: 'nonce', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'nonce',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'setGuard',
    inputs: [{ name: 'guard', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getOwners',
    inputs: [],
    outputs: [{ name: '', type: 'address[]', internalType: 'address[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isOwner',
    inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getThreshold',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
] as const;
